export const projectsList = [{
  title: "Todo App",
  imgSrc: "/toDoAppUi.png",
  description: "A simple task management application(ToDo app) to help users organize their daily tasks.",
  skill: "React, Redux, HTML,CSS,JS",
  features: "Features: Task creation, deletion, and completion",
  live: "https://drive.google.com/file/d/1PsCSAxpv6F6R9G_2aBpBRiLnlv260RnZ/view?usp=sharing",
  github: "https://github.com/vinithp03/Vinith-React_ToDo_App/tree/main",
}, {
  title: "E-commerce website ui",
  imgSrc: "/myntraClone-ui.png",
  description: "An e-commerce web application that mimics the functionality of Myntra, including product listing and filtering.",
  skill: "React, Redux, HTML,CSS,JS",
  features: "Features: product display, Add to bag, responsive design",
  live: "https://drive.google.com/file/d/1Zm5AnlwThHaSoIe5eUdMKRhsEP2Y3YiF/view?usp=sharing",
  github: "https://github.com/vinithp03/Myntra-clone-react/tree/main",
},
{
  title: "Online ticket booking system",
  imgSrc: "/movieTicket.png",
  description: "React-based movie ticket booking application where users can select seats, view booking summaries, and proceed to payment",
  skill: "React, Redux, HTML,CSS,JS,Bootsrap",
  features: "Features: seat selection, view booking, adding food,and bill",
  live: "https://ticket-booking-app-react-js.vercel.app/",
  github: "https://github.com/vinithp03/TicketBooking-App-ReactJS.git",
},
{
  title: "Dynamic table with CRUD and pagination",
  imgSrc: "/dynamicTable.png",
  description: "This application allows users to manage a table of data with features like CRUD operations, search functionality, pagination, and editable table cells.",
  skill: "React, Redux, HTML,CSS,JS,Bootsrap",
  features: "Features: CRUD operations,searching,pagination",
  live: "https://crud-table-theta.vercel.app/",
  github: "https://github.com/vinithp03/CRUD-table.git",
},
];